In [1]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

from sklearn.ensemble import VotingClassifier

import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import LabelEncoder

from sklearn.metrics import confusion_matrix

In [2]:
# load the dataset

# Clone the repository containing the dataset
!git clone https://github.com/imharshitaa/Clinical-Decision-Support-System-Healthcare-EPICS-project.git

# Assuming the dataset file is in CSV format, you can use pandas to load it
df = pd.read_csv("Clinical-Decision-Support-System-Healthcare-EPICS-project/data/Patient Data.csv")

# Drop the 'Index' column
df.drop(columns=['Index'], inplace=True)

# Replace NaN values with 0
df.fillna(0, inplace=True)

# Now you can work with the modified dataset
print(df.head())



Cloning into 'Clinical-Decision-Support-System-Healthcare-EPICS-project'...
remote: Enumerating objects: 295, done.
remote: Counting objects: 100% (137/137), done.
remote: Compressing objects: 100% (131/131), done.
remote: Total 295 (delta 56), reused 0 (delta 0), pack-reused 158
Receiving objects: 100% (295/295), 24.08 MiB | 11.20 MiB/s, done.
Resolving deltas: 100% (189/189), done.
    HR (BPM)   RESP (BPM)   SpO2 (%)  TEMP (C)  PRIORITY
0       94.0         21.0       97.0      36.2    Normal
1       94.0         25.0       97.0      36.2    Normal
2      101.0         25.0       93.0      38.0  Abnormal
3       55.0         11.0      100.0      35.0  Abnormal
4       93.0         26.0       95.0      37.0    Normal


In [3]:
# split the data into features and target

X = df.iloc[0:,:-1].values

y = df.iloc[:,-1].values

np.nan_to_num(X,
copy=False)

np.nan_to_num(y,copy=False)

labelencoder_y = LabelEncoder()

y = labelencoder_y.fit_transform(y)

X_train, X_test, y_train, y_test =  train_test_split(X, y, test_size=0.20,random_state=0)

print("X_test")

print(X_test)

X_test
[[101.  17.  97.  40.]
 [ 90.  18.  97.  47.]
 [ 89.  19.  96.  42.]
 ...
 [ 82.  20.  93.  43.]
 [115.  18.  93.  37.]
 [ 76.  17.  98.  40.]]


In [4]:
#  the logistic regression model

logisticReg = LogisticRegression(random_state=95,max_iter=95)



#  the decision tree model

decisionTrClf = DecisionTreeClassifier(random_state=90)

In [5]:
#  ensemble model using both logistic regression and decision tree

ensemble = VotingClassifier(estimators=[('lr',logisticReg), ('dt',decisionTrClf)], voting='soft')



# fit the ensemble model to the data

ensemble.fit(X_train,y_train)

VotingClassifier(estimators=[('lr',
                              LogisticRegression(max_iter=95, random_state=95)),
                             ('dt', DecisionTreeClassifier(random_state=90))],
                 voting='soft')

In [6]:
# evaluate the model using k-fold cross-validation

from sklearn.model_selection import cross_val_score

scores = cross_val_score(ensemble,X_test, y_test, cv=5)

print("Accuracy:%0.2f (+/-%0.2f)" % (scores.mean(),scores.std() * 2))

def confusionMatrix(y_true,y_pred):
  y_pred = np.round(abs(y_pred))
  tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
  accuracy=(tp+tn)/(tp+fp+fn+tn)
  specificity = tn/(tn+fp)
  sensitivity=tp/(tp+fn)
  print("Accuracy:",accuracy*100)
  print("Sensitivity:",sensitivity*100)
  print("Specificity:",specificity*100)
y_pred = ensemble.predict(X_test)
confusionMatrix(y_test,y_pred)

Accuracy:0.99 (+/-0.01)
Accuracy: 99.64698960580506
Sensitivity: 99.49238578680203
Specificity: 99.69364309420476


In [7]:
import pickle

filename = 'file.sav'

pickle.dump(ensemble,open(filename,'wb'))

# load the model from disk

loaded_model = pickle.load(open(filename,'rb'))

result = loaded_model.score(X_test, y_test)

print("Loaded model")

print(result)



Loaded model
0.9964698960580506


In [8]:
Z = [94,26,97,29],[94,25,97,42],[110,16,97,45],[142,10,97,45],[110,16,98,31]
Z = np.array(Z)

#Z = Z.reshape(-1,1)
print("ZZZZZZZZZZZZz")
print(Z)


ZZZZZZZZZZZZz
[[ 94  26  97  29]
 [ 94  25  97  42]
 [110  16  97  45]
 [142  10  97  45]
 [110  16  98  31]]


In [9]:
#Z_pred = new_model.predict(Z)
#print(Z_pred)



Num = 1
for z in Z:
    print(z)
    z = z.reshape(1,-1)
    #Z1_pred = model.predict(z)
    #print('Z1predddd')
    #print(Z1_pred)
    Z_pred = loaded_model.predict(z)
    print("line 265")
    print(Z_pred)


[94 26 97 29]
line 265
[1]
[94 25 97 42]
line 265
[0]
[110  16  97  45]
line 265
[0]
[142  10  97  45]
line 265
[0]
[110  16  98  31]
line 265
[1]
